---@meta


---Constants for the character names.
---@alias CharacterType
---| `CHARACTER_MARIO` Mario.
---| `CHARACTER_LUIGI` Luigi.
---| `CHARACTER_PEACH` Peach.
---| `CHARACTER_TOAD` Toad.
---| `CHARACTER_LINK` Link.
---| `CHARACTER_MEGAMAN` Megaman.
---| `CHARACTER_WARIO` Wario.
---| `CHARACTER_BOWSER` Bowser.
---| `CHARACTER_KLONOA` Klonoa.
---| `CHARACTER_NINJABOMBERMAN` Ninja Bomberman.
---| `CHARACTER_ROSALINA` Rosalina.
---| `CHARACTER_SNAKE` Snake.
---| `CHARACTER_ZELDA` Zelda.
---| `CHARACTER_ULTIMATERINKA` Ultimate Rinka.
---| `CHARACTER_UNCLEBROADSWORD` Uncle Broadsword.
---| `CHARACTER_SAMUS` Samus.

CHARACTER_MARIO = 1
CHARACTER_LUIGI = 2
CHARACTER_PEACH = 3
CHARACTER_TOAD = 4
CHARACTER_LINK = 5
CHARACTER_MEGAMAN = 6
CHARACTER_WARIO = 7
CHARACTER_BOWSER = 8
CHARACTER_KLONOA = 9
CHARACTER_NINJABOMBERMAN = 10
CHARACTER_ROSALINA = 11
CHARACTER_SNAKE = 12
CHARACTER_ZELDA = 13
CHARACTER_ULTIMATERINKA = 14
CHARACTER_UNCLEBROADSWORD = 15
CHARACTER_SAMUS = 16
